# Generated by Django 5.2.17 on 2026-09-02 07:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text='Identifies the tenant in URLs and in the tenant request header.', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='A slug may contain lowercase letters, digits and single hyphens.', regex='^[a-z0-9]+(-[a-z0-9]+)*$'), django.core.validators.MinLengthValidator(2)], verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('language', models.CharField(default='en', max_length=8, verbose_name='default language')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='time zone')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=16, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'indexes': [models.Index(fields=['user', 'is_active'], name='tenancy_mem_user_id_4a284b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='unique_membership_per_tenant')],
            },
        ),
    ]
