# Generated by Django 5.2.17 on 2026-09-02 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('rulepack', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('model_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='media.media', verbose_name='model file')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='rulepack.ruleset', verbose_name='rule set')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='task id')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='queued at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('engine_version', models.CharField(blank=True, max_length=64, verbose_name='engine version')),
                ('model_checksum', models.CharField(blank=True, max_length=64, verbose_name='model SHA-256')),
                ('rule_set_checksum', models.CharField(blank=True, max_length=64, verbose_name='rule set SHA-256')),
                ('outcome', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('INDETERMINATE', 'Indeterminate')], db_index=True, max_length=16, verbose_name='outcome')),
                ('specifications_passed', models.PositiveIntegerField(default=0, verbose_name='specifications passed')),
                ('specifications_failed', models.PositiveIntegerField(default=0, verbose_name='specifications failed')),
                ('specifications_indeterminate', models.PositiveIntegerField(default=0, verbose_name='specifications indeterminate')),
                ('passed', models.PositiveIntegerField(default=0, verbose_name='elements passed')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='elements failed')),
                ('indeterminate', models.PositiveIntegerField(default=0, verbose_name='elements indeterminate')),
                ('report', models.JSONField(blank=True, null=True, verbose_name='report')),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_model', 'The model file could not be read'), ('invalid_rule_set', 'The rule set could not be read'), ('stalled', 'The check stopped responding and was ended'), ('internal_error', 'The check failed unexpectedly')], max_length=32, verbose_name='failure reason')),
                ('failure_detail', models.TextField(blank=True, verbose_name='failure detail')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_check_runs', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant', verbose_name='tenant')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='review.review', verbose_name='review')),
            ],
            options={
                'verbose_name': 'check run',
                'verbose_name_plural': 'check runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['tenant', '-created_at'], name='review_revi_tenant__3686b6_idx'),
        ),
        migrations.AddIndex(
            model_name='checkrun',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='review_chec_tenant__8d9182_idx'),
        ),
        migrations.AddIndex(
            model_name='checkrun',
            index=models.Index(fields=['review', '-created_at'], name='review_chec_review__ad983f_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'succeeded'), _negated=True), ('report__isnull', False), _connector='OR'), name='succeeded_run_has_a_report'),
        ),
        migrations.AddConstraint(
            model_name='checkrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), models.Q(('failure_reason', ''), _negated=True), _connector='OR'), name='failed_run_states_a_reason'),
        ),
    ]
