# Generated by Django 5.2.17 on 2026-09-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('rulepack', '0002_rulepack'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrun',
            name='rule_pack_selection',
            field=models.JSONField(blank=True, default=list, verbose_name='rule pack selection'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rule_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='rulepack.ruleset', verbose_name='rule set'),
        ),
    ]
