# Generated by Django 5.2.17 on 2026-09-03 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_kind'),
        ('review', '0002_checkrun_rule_pack_selection_alter_review_rule_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrun',
            name='report_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_for_runs', to='media.media', verbose_name='report file'),
        ),
        migrations.AlterField(
            model_name='checkrun',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('invalid_model', 'The model file could not be read'), ('invalid_rule_set', 'The rule set could not be read'), ('stalled', 'The check stopped responding and was ended'), ('internal_error', 'The check failed unexpectedly'), ('rule_pack_modified', 'A cited rule pack no longer matches the bytes this run recorded')], max_length=32, verbose_name='failure reason'),
        ),
    ]
