# Generated by Django 5.2.17 on 2026-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_checkrun_report_file_alter_checkrun_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrun',
            name='report_generation_detail',
            field=models.TextField(blank=True, verbose_name='report generation detail'),
        ),
        migrations.AddField(
            model_name='checkrun',
            name='report_generation_error',
            field=models.CharField(blank=True, choices=[('too_large', 'The rendered report is larger than this system can store')], max_length=32, verbose_name='report generation error'),
        ),
    ]
