# Generated by Django 5.2.17 on 2026-09-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_checkrun_report_generation_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrun',
            name='claim_count',
            field=models.PositiveIntegerField(default=0, verbose_name='claim count'),
        ),
        migrations.AlterField(
            model_name='checkrun',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('invalid_model', 'The model file could not be read'), ('invalid_rule_set', 'The rule set could not be read'), ('stalled', 'The check stopped responding and was ended'), ('internal_error', 'The check failed unexpectedly'), ('rule_pack_modified', 'A cited rule pack no longer matches the bytes this run recorded'), ('resource_exhausted', 'The check repeatedly failed to complete and was stopped rather than retried')], max_length=32, verbose_name='failure reason'),
        ),
    ]
