# Generated by hand for T-0073: `project` arrives nullable so this applies cleanly
# against a database that already has reviews. 0007 backfills every existing review onto
# a per-tenant "عمومی" project; 0008 makes the column non-nullable once every row has one.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('review', '0005_checkrun_claim_count_alter_checkrun_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='project.project', verbose_name='project'),
        ),
    ]
