# Generated by Django 5.2.17 on 2026-09-17, trimmed to T-0061's own change: adding
# `ReportGenerationFailure.OTHER`. The autodetector also proposed an `AlterField` on
# `failure_reason` -- pre-existing drift on `main`, unrelated to this task (reproduced by
# `makemigrations review --check --dry-run` before any of this task's edits) -- left out
# on purpose so this migration is only what this task actually changed.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_review_project_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrun',
            name='report_generation_error',
            field=models.CharField(blank=True, choices=[('too_large', 'The rendered report is larger than this system can store'), ('other', 'The rendered report could not be stored')], max_length=32, verbose_name='report generation error'),
        ),
    ]
