"""Runs are nested under the review they belong to.

Written out rather than generated by a nested-router dependency: two routes are cheaper to
read here than a library is to reason about.
"""

from __future__ import annotations

from django.urls import include, path

from cadgpt.apps.base.drf.routers import ScopedRouter
from cadgpt.apps.review.api.v1.views import CheckRunViewSet, ReviewViewSet

app_name = "review-v1"

router = ScopedRouter(scope="tenant")
router.register("reviews", ReviewViewSet, basename="review")

run_list = CheckRunViewSet.as_view({"get": "list"})
run_detail = CheckRunViewSet.as_view({"get": "retrieve"})

urlpatterns = [
    path("", include(router.urls)),
    path(
        "reviews/<uuid:review_uuid>/runs/",
        run_list,
        name="tenant-review-run-list",
    ),
    path(
        "reviews/<uuid:review_uuid>/runs/<uuid:uuid>/",
        run_detail,
        name="tenant-review-run-detail",
    ),
]
