# Generated by Django 5.2.17 on 2026-09-02 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='declared title')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='declared author')),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='declared version')),
                ('specification_count', models.PositiveIntegerField(default=0, verbose_name='specifications')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rule_sets', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_sets', to='media.media', verbose_name='source file')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'rule set',
                'verbose_name_plural': 'rule sets',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='unique_active_rule_set_name_per_tenant')],
            },
        ),
    ]
