# Generated by Django 5.2.17 on 2026-09-02 18:03

import cadgpt.apps.rulepack.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulepack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('jurisdiction', models.CharField(max_length=64, verbose_name='jurisdiction')),
                ('region', models.CharField(blank=True, max_length=64, verbose_name='region')),
                ('version', models.CharField(max_length=64, verbose_name='pack version')),
                ('source_file', models.FileField(max_length=512, upload_to=cadgpt.apps.rulepack.models.rule_pack_upload_to, verbose_name='source file')),
                ('source_citation', models.TextField(verbose_name='source citation')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='declared title')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='declared author')),
                ('specification_count', models.PositiveIntegerField(default=0, verbose_name='specifications')),
            ],
            options={
                'verbose_name': 'rule pack',
                'verbose_name_plural': 'rule packs',
                'ordering': ('jurisdiction', 'region', 'name', 'version'),
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'region', 'version', 'name'), name='unique_rule_pack_identity')],
            },
        ),
    ]
