import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `public/mockServiceWorker.js` is vendored by `msw init`, like `schema.d.ts` is
  // generated by `openapi-typescript` -- neither is ours to style.
  { ignores: ["dist", "storybook-static", "src/api/schema.d.ts", "public/mockServiceWorker.js"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: { ecmaVersion: 2022 },
    plugins: { "react-hooks": reactHooks, "react-refresh": reactRefresh },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
  {
    // Playwright fixtures, not React: `test.extend` calls its callback `use`, which
    // react-hooks/rules-of-hooks otherwise mistakes for React 19's built-in `use` hook.
    files: ["e2e/**/*.ts"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
    },
  },
  {
    // A story file's whole purpose is to export story objects beside a component, which is
    // exactly what `only-export-components` exists to prevent in application modules. None
    // of these files is part of the bundle, so fast refresh has nothing to lose here.
    files: ["**/*.stories.tsx", ".storybook/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
);
