# Generated by Django 5.2.17 on 2026-09-02 07:21

import cadgpt.apps.media.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('file', models.FileField(max_length=512, upload_to=cadgpt.apps.media.models.upload_to, verbose_name='file')),
                ('kind', models.CharField(choices=[('ifc_model', 'IFC model'), ('ids_ruleset', 'IDS rule set')], max_length=32, verbose_name='kind')),
                ('original_name', models.CharField(max_length=255, verbose_name='original file name')),
                ('content_type', models.CharField(blank=True, max_length=128, verbose_name='content type')),
                ('size_bytes', models.BigIntegerField(verbose_name='size in bytes')),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant', verbose_name='tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'kind', '-created_at'], name='media_media_tenant__21e518_idx'), models.Index(fields=['tenant', 'checksum_sha256'], name='media_media_tenant__598d70_idx')],
            },
        ),
    ]
