# Generated by Django 5.2.17 on 2026-09-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='kind',
            field=models.CharField(choices=[('ifc_model', 'IFC model'), ('ids_ruleset', 'IDS rule set'), ('report', 'Generated report')], max_length=32, verbose_name='kind'),
        ),
    ]
