"""Derive the web brand assets from the master logo.

The master `cadgpt-logo.svg` is supplied artwork and is never edited. Two things are derived
from it, and both have been regenerated by hand more than once across attempts at the same
defect, each time with the numbers re-guessed -- which is what this script exists to stop.

1. `services/web/public/cadgpt-mark.svg` -- the same six paths, byte for byte, with the
   viewBox tightened. The master's `0 0 1024 1024` box is 59% empty, so a 28px slot in the
   topbar was rendering an 18px glyph.

   The box is squared **on the crosshair intersection**, not on the bounding box. The
   mark's four arms are deliberately unequal, so bbox-centring pushes the intersection
   off the tile's middle and the whole mark reads as sliding out of it -- which is what
   shipped on the first cut of this and was rejected on sight. Both values are measured
   here, not copied from a previous run.

2. `services/web/public/favicon.png` -- 64x64, with the plaque baked in. In the product the
   plaque is a CSS wrapper, but a browser's tab strip is a ground CSS cannot reach, and the
   strip may be light or dark depending on the browser's own theme. A near-white tile is the
   only treatment that reads on both: on a dark strip it is a crisp chip, and on a light one
   it is invisible while the mark's own navy carries it.

Run: `python3 scripts/build_brand_assets.py` from the repository root. Requires `convert`
(ImageMagick) for SVG rasterisation and Pillow for the tile compositing.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
MASTER = ROOT / "cadgpt-logo.svg"
PUBLIC = ROOT / "services" / "web" / "public"

MASTER_BOX = 1024
MEASURE_AT = 2048

FAVICON_SIZE = 64
FAVICON_MARK_RATIO = 0.80
FAVICON_RADIUS_RATIO = 3 / 16
PLAQUE_RGBA = (0xF2, 0xF5, 0xFF, 0xFF)  # --brand-plaque

SUPERSAMPLE = 8


def _rasterise(svg: Path, size: int, out: Path) -> None:
    convert = shutil.which("convert")
    if convert is None:
        raise SystemExit("ImageMagick's `convert` is not on PATH; cannot rasterise the SVG")
    # S603: every argument is a constant or a path this module built itself, and the
    # executable is resolved above rather than searched at call time. Nothing here crosses
    # a trust boundary -- this script reads one file in the repository and writes two.
    subprocess.run(  # noqa: S603
        [convert, "-background", "none", str(svg), "-resize", f"{size}x{size}", str(out)],
        check=True,
    )


def _master_paths() -> str:
    """The master's drawing, with its C2PA metadata block dropped.

    The metadata is a provenance manifest on the master and stays there; a derived raster
    could not carry it anyway, so neither does the derived vector.
    """
    source = MASTER.read_text()
    stripped = re.sub(r"<metadata>.*?</metadata>", "", source, flags=re.S)
    inner = re.search(r"<svg[^>]*>(.*)</svg>", stripped, flags=re.S)
    if inner is None:
        raise SystemExit(f"{MASTER} is not a single <svg> element")
    paths = re.findall(r'<path fill="(#[0-9A-Fa-f]{6})" d="([^"]+)"/>', inner.group(1))
    if len(paths) != 6:
        raise SystemExit(f"expected 6 paths in the master, found {len(paths)}")
    fills = {colour.upper() for colour, _ in paths}
    if fills != {"#3165EB", "#1B1456"}:
        raise SystemExit(f"the master's two colours have changed: {sorted(fills)}")
    return "\n  ".join(f'<path fill="{colour}" d="{data}"/>' for colour, data in paths)


Point = tuple[float, float]
Box = tuple[float, float, float, float]


def _crosshair_axes(alpha: Image.Image) -> tuple[Point, Box]:
    """Where the mark's two long strokes actually run.

    The mark's four arms are **not** the same length -- the horizontal stroke reaches
    further right than left, the vertical further up than down -- so the bounding box's
    centre is not the mark's centre. Centring a tile on the bbox slides the crosshair
    visibly down and to the left, which is what "the legs are not the same length so
    centring on the edges looks abnormal" describes. The eye locks onto the intersection,
    so that is what has to sit in the middle.

    Found by sampling each arm near its tip, where only that one stroke is present, and
    taking the middle of its band -- not by trusting the master's nominal centre.
    """
    width = alpha.size[0]
    pixels = alpha.load()
    box = alpha.getbbox()
    if box is None:
        raise SystemExit("the master rendered empty")
    x0, y0, x1, y1 = box

    def band_centre(fixed: int, span: range, horizontal: bool) -> float:
        hits = [i for i in span if pixels[(i, fixed) if horizontal else (fixed, i)] > 128]
        return (hits[0] + hits[-1]) / 2

    inset = round((x1 - x0) * 0.03)
    y_axis = [
        band_centre(x, range(y0, y1), False)
        for x in (x0 + inset, x0 + 2 * inset, x1 - 2 * inset, x1 - inset)
    ]
    x_axis = [
        band_centre(y, range(x0, x1), True)
        for y in (y0 + inset, y0 + 2 * inset, y1 - 2 * inset, y1 - inset)
    ]
    for name, samples in (("horizontal", y_axis), ("vertical", x_axis)):
        if max(samples) - min(samples) > width * 0.01:
            raise SystemExit(f"the {name} stroke is not straight: {samples}")
    scale = MASTER_BOX / width
    return (sum(x_axis) / len(x_axis) * scale, sum(y_axis) / len(y_axis) * scale), (
        x0 * scale,
        y0 * scale,
        x1 * scale,
        y1 * scale,
    )


def _measure_trim(work: Path) -> tuple[float, float, float]:
    """A square box centred on the crosshair, just big enough to hold every arm."""
    render = work / "measure.png"
    _rasterise(MASTER, MEASURE_AT, render)
    with Image.open(render) as image:
        (cx, cy), (x0, y0, x1, y1) = _crosshair_axes(image.getchannel("A"))
    reach = max(cx - x0, x1 - cx, cy - y0, y1 - cy)
    return cx - reach, cy - reach, reach * 2


def build_mark(work: Path) -> Path:
    left, top, side = _measure_trim(work)
    emptiness = 1 - ((side * side) / (MASTER_BOX * MASTER_BOX))
    out = PUBLIC / "cadgpt-mark.svg"
    out.write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{side:.0f}" height="{side:.0f}"'
        f' viewBox="{left:.0f} {top:.0f} {side:.0f} {side:.0f}">\n'
        "  <!-- Generated by scripts/build_brand_assets.py from cadgpt-logo.svg.\n"
        "       Do not edit. Geometry and both fills are the master's; only the viewBox\n"
        "       is tightened, squared on the crosshair intersection so the unequal arms\n"
        f"       stay optically centred. The master's box is {emptiness:.0%} empty. -->\n"
        f"  {_master_paths()}\n"
        "</svg>\n"
    )
    print(
        f"{out.relative_to(ROOT)}: viewBox {left:.0f} {top:.0f} {side:.0f} {side:.0f} "
        f"({emptiness:.0%} of the master's box was empty)"
    )
    return out


def build_favicon(mark: Path, work: Path) -> None:
    canvas = FAVICON_SIZE * SUPERSAMPLE
    tile = Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
    ImageDraw.Draw(tile).rounded_rectangle(
        (0, 0, canvas - 1, canvas - 1),
        radius=round(canvas * FAVICON_RADIUS_RATIO),
        fill=PLAQUE_RGBA,
    )
    glyph_px = round(canvas * FAVICON_MARK_RATIO)
    glyph_file = work / "glyph.png"
    _rasterise(mark, glyph_px, glyph_file)
    with Image.open(glyph_file) as glyph:
        glyph = glyph.convert("RGBA")
        tile.alpha_composite(
            glyph, ((canvas - glyph.width) // 2, (canvas - glyph.height) // 2)
        )
    out = PUBLIC / "favicon.png"
    tile.resize((FAVICON_SIZE, FAVICON_SIZE), Image.LANCZOS).save(out)
    print(
        f"{out.relative_to(ROOT)}: {FAVICON_SIZE}px tile, mark at {FAVICON_MARK_RATIO:.0%}"
    )


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        build_favicon(build_mark(work), work)


if __name__ == "__main__":
    main()
